### ISSUE TITLE
an amazing work except for interacting with existing go codes

### ISSUE THREAD

**Issue by Vegertar** [glycerine/zygomys#15]
You know, to call go codes, users have to declare zygo signatures, but clojure can use JDK library directly.
I think this is the biggest deal that we couldn't use zygo in production.
Thanks for your fantastic work.

**Comment by glycerine** [comment]
It's much worse than that. Not only does zygo require that you compile in the Go structs you want to refer to from zygo... you have to suffer along without being able to use libraries without compilation like other Go programs, since Go still lacks a plugin infrastructure. Also basic things in zygo will be slower than clojure, since we do have a mature JIT compiler like the JVM provides; zygo is a simple bytecode interpreter.
